# Generated by Django 5.1 on 2024-08-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_costomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='costomer',
            name='profile_pic',
        ),
    ]
