# Generated by Django 5.1 on 2024-08-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_costomer_name_remove_costomer_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costomer',
        ),
        migrations.DeleteModel(
            name='UserMaster',
        ),
    ]
