# Generated by Django 5.1 on 2024-08-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='mobile_otp',
        ),
    ]
