# Generated by Django 5.1 on 2024-08-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_usermaster_mobile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='email_otp',
        ),
    ]
