# Generated by Django 5.1 on 2024-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_usermaster_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomer',
            name='landmark',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costomer',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
