# Generated by Django 5.1 on 2024-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_costomer_landmark_costomer_pincode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costomer',
            new_name='Customer',
        ),
    ]
