# Generated by Django 5.1 on 2024-09-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Gst',
            field=models.IntegerField(),
        ),
    ]
