# Generated by Django 5.1 on 2024-09-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_gst_seller_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
