# Generated by Django 5.1 on 2024-09-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_seller_address_alter_seller_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.customer'),
        ),
    ]
