# Generated by Django 5.1 on 2024-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type_category',
        ),
        migrations.AddField(
            model_name='item',
            name='typecategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
