# Generated by Django 5.1 on 2024-09-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_item_type_category_item_typecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='typecategory',
            new_name='categorytype',
        ),
    ]
