# Generated by Django 5.1 on 2024-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_typecategory_item_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SellerItem/'),
        ),
    ]
