# Generated by Django 5.0.4 on 2024-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
