# Generated by Django 5.0.4 on 2024-09-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_item_discounted_price_item_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='original_price',
        ),
    ]
