# Generated by Django 5.0.4 on 2024-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='categorytype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
